import Image from "next/image";
import { ArrowDownRight, ArrowUpRight, Code2, BriefcaseBusiness, Mail, MapPin } from "lucide-react";
import { Navigation } from "@/components/navigation";
import { ContactForm } from "@/components/contact-form";
import { ProjectExplorer } from "@/components/project-explorer";
import { profile, skills, projects, experience, education } from "@/data/portfolio";

const External = ({ href, children }: { href: string; children: React.ReactNode }) => <a href={href} target="_blank" rel="noreferrer" className="text-link">{children}<ArrowUpRight size={15} /></a>;

export default function Home() { return <main><Navigation />
  <section id="home" className="hero shell"><div className="eyebrow"><span className="status-dot" /> Available for software engineering opportunities</div><div className="hero-grid"><div className="hero-intro"><p className="kicker">Software engineer · Python backend developer</p><h1><span>Kunal</span><br /><em>Gaikwad</em></h1><div className="hero-copy"><p>Building reliable APIs, data-driven web applications, and intelligent systems with a focus on the details that make products last.</p><div className="hero-actions"><a className="button button-primary" href="#work">Explore selected work <ArrowDownRight size={18} /></a><a className="button button-quiet" href="#contact">Let&apos;s connect <ArrowUpRight size={17} /></a></div></div></div><figure className="portrait-frame"><Image src="/images/kunal-gaikwad.png" alt="Kunal Gaikwad speaking at an event" fill priority sizes="(max-width: 800px) 100vw, 42vw" /><figcaption><span>Hyderabad, India</span><span>2026</span></figcaption></figure></div><div className="hero-foot"><span><MapPin size={15} /> Building with Python, data, and AI</span><span>Scroll to explore <ArrowDownRight size={15} /></span><span className="mono">BUILD → MEASURE → OPTIMIZE</span></div></section>
  <section id="about" className="section shell about"><div className="section-label">01 / ABOUT</div><div className="about-grid"><h2>Engineering judgment,<br /><em>full-stack execution.</em></h2><div className="prose"><p>I&apos;m a B.Tech Computer Science &amp; Engineering graduate focused on practical software systems: authenticated APIs, relational data models, responsive interfaces, and workflows that stay understandable as features grow.</p><p>My work sits at the intersection of backend engineering, data, and AI—turning real product requirements into clean, maintainable software.</p><a href="/Kunal_Gaikwad_Resume.pdf" target="_blank" className="inline-link">View résumé <ArrowUpRight size={16} /></a></div></div></section>
  <section id="work" className="section shell work"><div className="section-heading"><div className="section-label">02 / SELECTED WORK</div><p>High-signal applications selected for system design, product workflow, and engineering depth.</p></div><ProjectExplorer projects={projects} /><External href={profile.github}>See all repositories on GitHub</External></section>
  <section id="skills" className="section shell skills-section"><div className="section-heading"><div className="section-label">03 / TOOLKIT</div><h2>A backend-heavy stack with <em>product range.</em></h2></div><div className="skills-grid">{skills.map(group => <div className="skill-group" key={group.category}><h3>{group.category}</h3><p>{group.items.join(" · ")}</p></div>)}</div></section>
  <section id="experience" className="section shell experience-section"><div className="section-label">04 / EXPERIENCE &amp; EDUCATION</div><div className="timeline">{experience.map(item => <article className="timeline-row" key={item.company}><span className="mono">{item.period}</span><div><h3>{item.role}</h3><p className="timeline-place">{item.company} · {item.location}</p><p>{item.description}</p><ul>{item.highlights.map(highlight => <li key={highlight}>{highlight}</li>)}</ul></div></article>)}{education.map(item => <article className="timeline-row" key={item.institution}><span className="mono">{item.period}</span><div><h3>{item.degree}</h3><p className="timeline-place">{item.institution}</p><p>{item.description}</p></div></article>)}</div></section>
  <section id="contact" className="contact shell"><div><div className="section-label">05 / CONTACT</div><h2>Have a problem<br />worth <em>solving?</em></h2><p>Let&apos;s build something useful.</p><div className="contact-links"><External href={`mailto:${profile.email}`}><Mail size={16} /> {profile.email}</External><External href={profile.linkedin}><BriefcaseBusiness size={16} /> LinkedIn</External><External href={profile.github}><Code2 size={16} /> GitHub</External></div></div><ContactForm email={profile.email} /></section><footer className="footer shell"><span>© {new Date().getFullYear()} Kunal Gaikwad</span><span>Software Engineer</span><a href="#home">Back to top ↑</a></footer></main>; }
